name: Test

on:
  pull_request:
  push:

env:
  NODE_VERSION: "20.18.0"

jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: javascript

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        name: Cache Node development dependencies
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install Node development dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: lint
        shell: bash
        run: npm run lint

      - name: format
        shell: bash
        run: npm run format:check

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: javascript

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/cache@v3
        name: Cache Node development dependencies
        id: node-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ env.NODE_VERSION }}-${{ hashFiles('package-lock.json') }}

      - name: Install Node development dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        run: npm run test
